import { loadEntitiesFromRegistry } from "./load-entities";
import type { EntityConfig, EntityMeta } from "./types";
import rawEntityMetas from "./entity-metas.json";

export type {
  EntityConfig,
  EntityMeta,
  ReleaseItem,
  ReleaseHowTo,
  ReleaseAudience,
  ReleaseStatus,
  ThemeConfig,
} from "./types";
export { defaultTheme } from "./defaultTheme";

/** Full entity configs including releases — for server-side use (API routes, feeds, etc.) */
export const entities: EntityConfig[] = loadEntitiesFromRegistry();

export function getEntityById(id: string): EntityConfig | undefined {
  return entities.find((e) => e.id === id);
}

/**
 * Entity metadata WITHOUT releases — safe to statically import in client components.
 * Generated by `npm run gen-static-data` from the entity JSON files.
 */
export const entityMetas: EntityMeta[] = rawEntityMetas as EntityMeta[];
